/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/aead.proto */

#ifndef PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2faead_2eproto__INCLUDED
#define PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2faead_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct AeadDataMsg AeadDataMsg;


/* --- enums --- */


/* --- messages --- */

struct  AeadDataMsg
{
  ProtobufCMessage base;
  ProtobufCBinaryData key;
  ProtobufCBinaryData iv;
  uint32_t ivlen;
  ProtobufCBinaryData assoc;
  ProtobufCBinaryData tag;
  uint32_t taglen;
  uint64_t cipher;
  uint32_t ptlen;
  ProtobufCBinaryData data;
  uint32_t integrity_error;
};
#define AEAD_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aead_data_msg__descriptor) \
, {0,NULL}, {0,NULL}, 0, {0,NULL}, {0,NULL}, 0, 0, 0, {0,NULL}, 0 }


/* AeadDataMsg methods */
void   aead_data_msg__init
                     (AeadDataMsg         *message);
size_t aead_data_msg__get_packed_size
                     (const AeadDataMsg   *message);
size_t aead_data_msg__pack
                     (const AeadDataMsg   *message,
                      uint8_t             *out);
size_t aead_data_msg__pack_to_buffer
                     (const AeadDataMsg   *message,
                      ProtobufCBuffer     *buffer);
AeadDataMsg *
       aead_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aead_data_msg__free_unpacked
                     (AeadDataMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AeadDataMsg_Closure)
                 (const AeadDataMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor aead_data_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2faead_2eproto__INCLUDED */
