/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/cshake.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/cshake.pb-c.h"
void   cshake_data_msg__init
                     (CshakeDataMsg         *message)
{
  static const CshakeDataMsg init_value = CSHAKE_DATA_MSG__INIT;
  *message = init_value;
}
size_t cshake_data_msg__get_packed_size
                     (const CshakeDataMsg *message)
{
  assert(message->base.descriptor == &cshake_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cshake_data_msg__pack
                     (const CshakeDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cshake_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cshake_data_msg__pack_to_buffer
                     (const CshakeDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cshake_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CshakeDataMsg *
       cshake_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CshakeDataMsg *)
     protobuf_c_message_unpack (&cshake_data_msg__descriptor,
                                allocator, len, data);
}
void   cshake_data_msg__free_unpacked
                     (CshakeDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cshake_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cshake_data_msg__field_descriptors[9] =
{
  {
    "cipher",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(CshakeDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CshakeDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitlen",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CshakeDataMsg, bitlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outlen",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CshakeDataMsg, outlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minoutlen",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CshakeDataMsg, minoutlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxoutlen",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CshakeDataMsg, maxoutlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "function_name",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CshakeDataMsg, function_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "customization",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CshakeDataMsg, customization),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CshakeDataMsg, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cshake_data_msg__field_indices_by_name[] = {
  2,   /* field[2] = bitlen */
  0,   /* field[0] = cipher */
  7,   /* field[7] = customization */
  6,   /* field[6] = function_name */
  8,   /* field[8] = mac */
  5,   /* field[5] = maxoutlen */
  4,   /* field[4] = minoutlen */
  1,   /* field[1] = msg */
  3,   /* field[3] = outlen */
};
static const ProtobufCIntRange cshake_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor cshake_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CshakeDataMsg",
  "CshakeDataMsg",
  "CshakeDataMsg",
  "",
  sizeof(CshakeDataMsg),
  9,
  cshake_data_msg__field_descriptors,
  cshake_data_msg__field_indices_by_name,
  1,  cshake_data_msg__number_ranges,
  (ProtobufCMessageInit) cshake_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
