/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/cshake.proto */

#ifndef PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fcshake_2eproto__INCLUDED
#define PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fcshake_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct CshakeDataMsg CshakeDataMsg;


/* --- enums --- */


/* --- messages --- */

struct  CshakeDataMsg
{
  ProtobufCMessage base;
  uint64_t cipher;
  ProtobufCBinaryData msg;
  uint32_t bitlen;
  uint32_t outlen;
  uint32_t minoutlen;
  uint32_t maxoutlen;
  ProtobufCBinaryData function_name;
  ProtobufCBinaryData customization;
  ProtobufCBinaryData mac;
};
#define CSHAKE_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cshake_data_msg__descriptor) \
, 0, {0,NULL}, 0, 0, 0, 0, {0,NULL}, {0,NULL}, {0,NULL} }


/* CshakeDataMsg methods */
void   cshake_data_msg__init
                     (CshakeDataMsg         *message);
size_t cshake_data_msg__get_packed_size
                     (const CshakeDataMsg   *message);
size_t cshake_data_msg__pack
                     (const CshakeDataMsg   *message,
                      uint8_t             *out);
size_t cshake_data_msg__pack_to_buffer
                     (const CshakeDataMsg   *message,
                      ProtobufCBuffer     *buffer);
CshakeDataMsg *
       cshake_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cshake_data_msg__free_unpacked
                     (CshakeDataMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CshakeDataMsg_Closure)
                 (const CshakeDataMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cshake_data_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fcshake_2eproto__INCLUDED */
