/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/drbg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/drbg.pb-c.h"
void   drbg_data_msg__init
                     (DrbgDataMsg         *message)
{
  static const DrbgDataMsg init_value = DRBG_DATA_MSG__INIT;
  *message = init_value;
}
size_t drbg_data_msg__get_packed_size
                     (const DrbgDataMsg *message)
{
  assert(message->base.descriptor == &drbg_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drbg_data_msg__pack
                     (const DrbgDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drbg_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drbg_data_msg__pack_to_buffer
                     (const DrbgDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drbg_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DrbgDataMsg *
       drbg_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DrbgDataMsg *)
     protobuf_c_message_unpack (&drbg_data_msg__descriptor,
                                allocator, len, data);
}
void   drbg_data_msg__free_unpacked
                     (DrbgDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drbg_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor drbg_data_msg__field_descriptors[17] =
{
  {
    "entropy",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, entropy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pers",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, pers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addtl_reseed1",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, addtl_reseed1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addtl_reseed2",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, addtl_reseed2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entropy_reseed1",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, entropy_reseed1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entropy_reseed2",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, entropy_reseed2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addtl_generate1",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, addtl_generate1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addtl_generate2",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, addtl_generate2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entropy_generate1",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, entropy_generate1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entropy_generate2",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, entropy_generate2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "random",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, random),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rnd_data_bits_len",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, rnd_data_bits_len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pr",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, pr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "df",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DrbgDataMsg, df),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drbg_data_msg__field_indices_by_name[] = {
  7,   /* field[7] = addtl_generate1 */
  8,   /* field[8] = addtl_generate2 */
  3,   /* field[3] = addtl_reseed1 */
  4,   /* field[4] = addtl_reseed2 */
  13,   /* field[13] = cipher */
  16,   /* field[16] = df */
  0,   /* field[0] = entropy */
  9,   /* field[9] = entropy_generate1 */
  10,   /* field[10] = entropy_generate2 */
  5,   /* field[5] = entropy_reseed1 */
  6,   /* field[6] = entropy_reseed2 */
  1,   /* field[1] = nonce */
  2,   /* field[2] = pers */
  15,   /* field[15] = pr */
  11,   /* field[11] = random */
  14,   /* field[14] = rnd_data_bits_len */
  12,   /* field[12] = type */
};
static const ProtobufCIntRange drbg_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor drbg_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DrbgDataMsg",
  "DrbgDataMsg",
  "DrbgDataMsg",
  "",
  sizeof(DrbgDataMsg),
  17,
  drbg_data_msg__field_descriptors,
  drbg_data_msg__field_indices_by_name,
  1,  drbg_data_msg__number_ranges,
  (ProtobufCMessageInit) drbg_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
