/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/drbg.proto */

#ifndef PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fdrbg_2eproto__INCLUDED
#define PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fdrbg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct DrbgDataMsg DrbgDataMsg;


/* --- enums --- */


/* --- messages --- */

struct  DrbgDataMsg
{
  ProtobufCMessage base;
  ProtobufCBinaryData entropy;
  ProtobufCBinaryData nonce;
  ProtobufCBinaryData pers;
  ProtobufCBinaryData addtl_reseed1;
  ProtobufCBinaryData addtl_reseed2;
  ProtobufCBinaryData entropy_reseed1;
  ProtobufCBinaryData entropy_reseed2;
  ProtobufCBinaryData addtl_generate1;
  ProtobufCBinaryData addtl_generate2;
  ProtobufCBinaryData entropy_generate1;
  ProtobufCBinaryData entropy_generate2;
  ProtobufCBinaryData random;
  uint64_t type;
  uint64_t cipher;
  uint32_t rnd_data_bits_len;
  uint32_t pr;
  uint32_t df;
};
#define DRBG_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&drbg_data_msg__descriptor) \
, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, 0, 0, 0, 0, 0 }


/* DrbgDataMsg methods */
void   drbg_data_msg__init
                     (DrbgDataMsg         *message);
size_t drbg_data_msg__get_packed_size
                     (const DrbgDataMsg   *message);
size_t drbg_data_msg__pack
                     (const DrbgDataMsg   *message,
                      uint8_t             *out);
size_t drbg_data_msg__pack_to_buffer
                     (const DrbgDataMsg   *message,
                      ProtobufCBuffer     *buffer);
DrbgDataMsg *
       drbg_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   drbg_data_msg__free_unpacked
                     (DrbgDataMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DrbgDataMsg_Closure)
                 (const DrbgDataMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor drbg_data_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fdrbg_2eproto__INCLUDED */
