/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/ecdh.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/ecdh.pb-c.h"
void   ecdh_ss_data_msg__init
                     (EcdhSsDataMsg         *message)
{
  static const EcdhSsDataMsg init_value = ECDH_SS_DATA_MSG__INIT;
  *message = init_value;
}
size_t ecdh_ss_data_msg__get_packed_size
                     (const EcdhSsDataMsg *message)
{
  assert(message->base.descriptor == &ecdh_ss_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecdh_ss_data_msg__pack
                     (const EcdhSsDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ecdh_ss_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecdh_ss_data_msg__pack_to_buffer
                     (const EcdhSsDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ecdh_ss_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EcdhSsDataMsg *
       ecdh_ss_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EcdhSsDataMsg *)
     protobuf_c_message_unpack (&ecdh_ss_data_msg__descriptor,
                                allocator, len, data);
}
void   ecdh_ss_data_msg__free_unpacked
                     (EcdhSsDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ecdh_ss_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecdh_ss_ver_data_msg__init
                     (EcdhSsVerDataMsg         *message)
{
  static const EcdhSsVerDataMsg init_value = ECDH_SS_VER_DATA_MSG__INIT;
  *message = init_value;
}
size_t ecdh_ss_ver_data_msg__get_packed_size
                     (const EcdhSsVerDataMsg *message)
{
  assert(message->base.descriptor == &ecdh_ss_ver_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecdh_ss_ver_data_msg__pack
                     (const EcdhSsVerDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ecdh_ss_ver_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecdh_ss_ver_data_msg__pack_to_buffer
                     (const EcdhSsVerDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ecdh_ss_ver_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EcdhSsVerDataMsg *
       ecdh_ss_ver_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EcdhSsVerDataMsg *)
     protobuf_c_message_unpack (&ecdh_ss_ver_data_msg__descriptor,
                                allocator, len, data);
}
void   ecdh_ss_ver_data_msg__free_unpacked
                     (EcdhSsVerDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ecdh_ss_ver_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ecdh_ss_data_msg__field_descriptors[7] =
{
  {
    "cipher",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(EcdhSsDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Qxrem",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsDataMsg, qxrem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Qyrem",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsDataMsg, qyrem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "privloc",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsDataMsg, privloc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Qxloc",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsDataMsg, qxloc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Qyloc",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsDataMsg, qyloc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hashzz",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsDataMsg, hashzz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecdh_ss_data_msg__field_indices_by_name[] = {
  4,   /* field[4] = Qxloc */
  1,   /* field[1] = Qxrem */
  5,   /* field[5] = Qyloc */
  2,   /* field[2] = Qyrem */
  0,   /* field[0] = cipher */
  6,   /* field[6] = hashzz */
  3,   /* field[3] = privloc */
};
static const ProtobufCIntRange ecdh_ss_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ecdh_ss_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EcdhSsDataMsg",
  "EcdhSsDataMsg",
  "EcdhSsDataMsg",
  "",
  sizeof(EcdhSsDataMsg),
  7,
  ecdh_ss_data_msg__field_descriptors,
  ecdh_ss_data_msg__field_indices_by_name,
  1,  ecdh_ss_data_msg__number_ranges,
  (ProtobufCMessageInit) ecdh_ss_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecdh_ss_ver_data_msg__field_descriptors[8] =
{
  {
    "cipher",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(EcdhSsVerDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Qxrem",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsVerDataMsg, qxrem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Qyrem",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsVerDataMsg, qyrem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "privloc",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsVerDataMsg, privloc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Qxloc",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsVerDataMsg, qxloc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Qyloc",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsVerDataMsg, qyloc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hashzz",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EcdhSsVerDataMsg, hashzz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "validity_success",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EcdhSsVerDataMsg, validity_success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecdh_ss_ver_data_msg__field_indices_by_name[] = {
  4,   /* field[4] = Qxloc */
  1,   /* field[1] = Qxrem */
  5,   /* field[5] = Qyloc */
  2,   /* field[2] = Qyrem */
  0,   /* field[0] = cipher */
  6,   /* field[6] = hashzz */
  3,   /* field[3] = privloc */
  7,   /* field[7] = validity_success */
};
static const ProtobufCIntRange ecdh_ss_ver_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ecdh_ss_ver_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EcdhSsVerDataMsg",
  "EcdhSsVerDataMsg",
  "EcdhSsVerDataMsg",
  "",
  sizeof(EcdhSsVerDataMsg),
  8,
  ecdh_ss_ver_data_msg__field_descriptors,
  ecdh_ss_ver_data_msg__field_indices_by_name,
  1,  ecdh_ss_ver_data_msg__number_ranges,
  (ProtobufCMessageInit) ecdh_ss_ver_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
