/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/ecdh.proto */

#ifndef PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fecdh_2eproto__INCLUDED
#define PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fecdh_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct EcdhSsDataMsg EcdhSsDataMsg;
typedef struct EcdhSsVerDataMsg EcdhSsVerDataMsg;


/* --- enums --- */


/* --- messages --- */

struct  EcdhSsDataMsg
{
  ProtobufCMessage base;
  uint64_t cipher;
  ProtobufCBinaryData qxrem;
  ProtobufCBinaryData qyrem;
  ProtobufCBinaryData privloc;
  ProtobufCBinaryData qxloc;
  ProtobufCBinaryData qyloc;
  ProtobufCBinaryData hashzz;
};
#define ECDH_SS_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ecdh_ss_data_msg__descriptor) \
, 0, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL} }


struct  EcdhSsVerDataMsg
{
  ProtobufCMessage base;
  uint64_t cipher;
  ProtobufCBinaryData qxrem;
  ProtobufCBinaryData qyrem;
  ProtobufCBinaryData privloc;
  ProtobufCBinaryData qxloc;
  ProtobufCBinaryData qyloc;
  ProtobufCBinaryData hashzz;
  uint32_t validity_success;
};
#define ECDH_SS_VER_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ecdh_ss_ver_data_msg__descriptor) \
, 0, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, 0 }


/* EcdhSsDataMsg methods */
void   ecdh_ss_data_msg__init
                     (EcdhSsDataMsg         *message);
size_t ecdh_ss_data_msg__get_packed_size
                     (const EcdhSsDataMsg   *message);
size_t ecdh_ss_data_msg__pack
                     (const EcdhSsDataMsg   *message,
                      uint8_t             *out);
size_t ecdh_ss_data_msg__pack_to_buffer
                     (const EcdhSsDataMsg   *message,
                      ProtobufCBuffer     *buffer);
EcdhSsDataMsg *
       ecdh_ss_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ecdh_ss_data_msg__free_unpacked
                     (EcdhSsDataMsg *message,
                      ProtobufCAllocator *allocator);
/* EcdhSsVerDataMsg methods */
void   ecdh_ss_ver_data_msg__init
                     (EcdhSsVerDataMsg         *message);
size_t ecdh_ss_ver_data_msg__get_packed_size
                     (const EcdhSsVerDataMsg   *message);
size_t ecdh_ss_ver_data_msg__pack
                     (const EcdhSsVerDataMsg   *message,
                      uint8_t             *out);
size_t ecdh_ss_ver_data_msg__pack_to_buffer
                     (const EcdhSsVerDataMsg   *message,
                      ProtobufCBuffer     *buffer);
EcdhSsVerDataMsg *
       ecdh_ss_ver_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ecdh_ss_ver_data_msg__free_unpacked
                     (EcdhSsVerDataMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*EcdhSsDataMsg_Closure)
                 (const EcdhSsDataMsg *message,
                  void *closure_data);
typedef void (*EcdhSsVerDataMsg_Closure)
                 (const EcdhSsVerDataMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ecdh_ss_data_msg__descriptor;
extern const ProtobufCMessageDescriptor ecdh_ss_ver_data_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fecdh_2eproto__INCLUDED */
