/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/eddsa.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/eddsa.pb-c.h"
void   eddsa_keygen_data_msg__init
                     (EddsaKeygenDataMsg         *message)
{
  static const EddsaKeygenDataMsg init_value = EDDSA_KEYGEN_DATA_MSG__INIT;
  *message = init_value;
}
size_t eddsa_keygen_data_msg__get_packed_size
                     (const EddsaKeygenDataMsg *message)
{
  assert(message->base.descriptor == &eddsa_keygen_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eddsa_keygen_data_msg__pack
                     (const EddsaKeygenDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eddsa_keygen_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eddsa_keygen_data_msg__pack_to_buffer
                     (const EddsaKeygenDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eddsa_keygen_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EddsaKeygenDataMsg *
       eddsa_keygen_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EddsaKeygenDataMsg *)
     protobuf_c_message_unpack (&eddsa_keygen_data_msg__descriptor,
                                allocator, len, data);
}
void   eddsa_keygen_data_msg__free_unpacked
                     (EddsaKeygenDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &eddsa_keygen_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   eddsa_keyver_data_msg__init
                     (EddsaKeyverDataMsg         *message)
{
  static const EddsaKeyverDataMsg init_value = EDDSA_KEYVER_DATA_MSG__INIT;
  *message = init_value;
}
size_t eddsa_keyver_data_msg__get_packed_size
                     (const EddsaKeyverDataMsg *message)
{
  assert(message->base.descriptor == &eddsa_keyver_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eddsa_keyver_data_msg__pack
                     (const EddsaKeyverDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eddsa_keyver_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eddsa_keyver_data_msg__pack_to_buffer
                     (const EddsaKeyverDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eddsa_keyver_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EddsaKeyverDataMsg *
       eddsa_keyver_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EddsaKeyverDataMsg *)
     protobuf_c_message_unpack (&eddsa_keyver_data_msg__descriptor,
                                allocator, len, data);
}
void   eddsa_keyver_data_msg__free_unpacked
                     (EddsaKeyverDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &eddsa_keyver_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   eddsa_siggen_data_msg__init
                     (EddsaSiggenDataMsg         *message)
{
  static const EddsaSiggenDataMsg init_value = EDDSA_SIGGEN_DATA_MSG__INIT;
  *message = init_value;
}
size_t eddsa_siggen_data_msg__get_packed_size
                     (const EddsaSiggenDataMsg *message)
{
  assert(message->base.descriptor == &eddsa_siggen_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eddsa_siggen_data_msg__pack
                     (const EddsaSiggenDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eddsa_siggen_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eddsa_siggen_data_msg__pack_to_buffer
                     (const EddsaSiggenDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eddsa_siggen_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EddsaSiggenDataMsg *
       eddsa_siggen_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EddsaSiggenDataMsg *)
     protobuf_c_message_unpack (&eddsa_siggen_data_msg__descriptor,
                                allocator, len, data);
}
void   eddsa_siggen_data_msg__free_unpacked
                     (EddsaSiggenDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &eddsa_siggen_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   eddsa_sigver_data_msg__init
                     (EddsaSigverDataMsg         *message)
{
  static const EddsaSigverDataMsg init_value = EDDSA_SIGVER_DATA_MSG__INIT;
  *message = init_value;
}
size_t eddsa_sigver_data_msg__get_packed_size
                     (const EddsaSigverDataMsg *message)
{
  assert(message->base.descriptor == &eddsa_sigver_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eddsa_sigver_data_msg__pack
                     (const EddsaSigverDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eddsa_sigver_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eddsa_sigver_data_msg__pack_to_buffer
                     (const EddsaSigverDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eddsa_sigver_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EddsaSigverDataMsg *
       eddsa_sigver_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EddsaSigverDataMsg *)
     protobuf_c_message_unpack (&eddsa_sigver_data_msg__descriptor,
                                allocator, len, data);
}
void   eddsa_sigver_data_msg__free_unpacked
                     (EddsaSigverDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &eddsa_sigver_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   eddsa_keygen_en_msg__init
                     (EddsaKeygenEnMsg         *message)
{
  static const EddsaKeygenEnMsg init_value = EDDSA_KEYGEN_EN_MSG__INIT;
  *message = init_value;
}
size_t eddsa_keygen_en_msg__get_packed_size
                     (const EddsaKeygenEnMsg *message)
{
  assert(message->base.descriptor == &eddsa_keygen_en_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eddsa_keygen_en_msg__pack
                     (const EddsaKeygenEnMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eddsa_keygen_en_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eddsa_keygen_en_msg__pack_to_buffer
                     (const EddsaKeygenEnMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eddsa_keygen_en_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EddsaKeygenEnMsg *
       eddsa_keygen_en_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EddsaKeygenEnMsg *)
     protobuf_c_message_unpack (&eddsa_keygen_en_msg__descriptor,
                                allocator, len, data);
}
void   eddsa_keygen_en_msg__free_unpacked
                     (EddsaKeygenEnMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &eddsa_keygen_en_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   eddsa_free_key_msg__init
                     (EddsaFreeKeyMsg         *message)
{
  static const EddsaFreeKeyMsg init_value = EDDSA_FREE_KEY_MSG__INIT;
  *message = init_value;
}
size_t eddsa_free_key_msg__get_packed_size
                     (const EddsaFreeKeyMsg *message)
{
  assert(message->base.descriptor == &eddsa_free_key_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eddsa_free_key_msg__pack
                     (const EddsaFreeKeyMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eddsa_free_key_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eddsa_free_key_msg__pack_to_buffer
                     (const EddsaFreeKeyMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eddsa_free_key_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EddsaFreeKeyMsg *
       eddsa_free_key_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EddsaFreeKeyMsg *)
     protobuf_c_message_unpack (&eddsa_free_key_msg__descriptor,
                                allocator, len, data);
}
void   eddsa_free_key_msg__free_unpacked
                     (EddsaFreeKeyMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &eddsa_free_key_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor eddsa_keygen_data_msg__field_descriptors[3] =
{
  {
    "d",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaKeygenDataMsg, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaKeygenDataMsg, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(EddsaKeygenDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eddsa_keygen_data_msg__field_indices_by_name[] = {
  2,   /* field[2] = cipher */
  0,   /* field[0] = d */
  1,   /* field[1] = q */
};
static const ProtobufCIntRange eddsa_keygen_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor eddsa_keygen_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EddsaKeygenDataMsg",
  "EddsaKeygenDataMsg",
  "EddsaKeygenDataMsg",
  "",
  sizeof(EddsaKeygenDataMsg),
  3,
  eddsa_keygen_data_msg__field_descriptors,
  eddsa_keygen_data_msg__field_indices_by_name,
  1,  eddsa_keygen_data_msg__number_ranges,
  (ProtobufCMessageInit) eddsa_keygen_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor eddsa_keyver_data_msg__field_descriptors[3] =
{
  {
    "q",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaKeyverDataMsg, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(EddsaKeyverDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keyver_success",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EddsaKeyverDataMsg, keyver_success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eddsa_keyver_data_msg__field_indices_by_name[] = {
  1,   /* field[1] = cipher */
  2,   /* field[2] = keyver_success */
  0,   /* field[0] = q */
};
static const ProtobufCIntRange eddsa_keyver_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor eddsa_keyver_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EddsaKeyverDataMsg",
  "EddsaKeyverDataMsg",
  "EddsaKeyverDataMsg",
  "",
  sizeof(EddsaKeyverDataMsg),
  3,
  eddsa_keyver_data_msg__field_descriptors,
  eddsa_keyver_data_msg__field_indices_by_name,
  1,  eddsa_keyver_data_msg__number_ranges,
  (ProtobufCMessageInit) eddsa_keyver_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor eddsa_siggen_data_msg__field_descriptors[7] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaSiggenDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaSiggenDataMsg, context),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaSiggenDataMsg, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaSiggenDataMsg, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(EddsaSiggenDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prehash",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EddsaSiggenDataMsg, prehash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "privkey",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EddsaSiggenDataMsg, privkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eddsa_siggen_data_msg__field_indices_by_name[] = {
  4,   /* field[4] = cipher */
  1,   /* field[1] = context */
  0,   /* field[0] = msg */
  5,   /* field[5] = prehash */
  6,   /* field[6] = privkey */
  2,   /* field[2] = q */
  3,   /* field[3] = signature */
};
static const ProtobufCIntRange eddsa_siggen_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor eddsa_siggen_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EddsaSiggenDataMsg",
  "EddsaSiggenDataMsg",
  "EddsaSiggenDataMsg",
  "",
  sizeof(EddsaSiggenDataMsg),
  7,
  eddsa_siggen_data_msg__field_descriptors,
  eddsa_siggen_data_msg__field_indices_by_name,
  1,  eddsa_siggen_data_msg__number_ranges,
  (ProtobufCMessageInit) eddsa_siggen_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor eddsa_sigver_data_msg__field_descriptors[6] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaSigverDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaSigverDataMsg, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaSigverDataMsg, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(EddsaSigverDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prehash",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EddsaSigverDataMsg, prehash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sigver_success",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EddsaSigverDataMsg, sigver_success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eddsa_sigver_data_msg__field_indices_by_name[] = {
  3,   /* field[3] = cipher */
  0,   /* field[0] = msg */
  4,   /* field[4] = prehash */
  1,   /* field[1] = q */
  2,   /* field[2] = signature */
  5,   /* field[5] = sigver_success */
};
static const ProtobufCIntRange eddsa_sigver_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor eddsa_sigver_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EddsaSigverDataMsg",
  "EddsaSigverDataMsg",
  "EddsaSigverDataMsg",
  "",
  sizeof(EddsaSigverDataMsg),
  6,
  eddsa_sigver_data_msg__field_descriptors,
  eddsa_sigver_data_msg__field_indices_by_name,
  1,  eddsa_sigver_data_msg__number_ranges,
  (ProtobufCMessageInit) eddsa_sigver_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor eddsa_keygen_en_msg__field_descriptors[3] =
{
  {
    "curve",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(EddsaKeygenEnMsg, curve),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qbuf",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EddsaKeygenEnMsg, qbuf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "privkey",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EddsaKeygenEnMsg, privkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eddsa_keygen_en_msg__field_indices_by_name[] = {
  0,   /* field[0] = curve */
  2,   /* field[2] = privkey */
  1,   /* field[1] = qbuf */
};
static const ProtobufCIntRange eddsa_keygen_en_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor eddsa_keygen_en_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EddsaKeygenEnMsg",
  "EddsaKeygenEnMsg",
  "EddsaKeygenEnMsg",
  "",
  sizeof(EddsaKeygenEnMsg),
  3,
  eddsa_keygen_en_msg__field_descriptors,
  eddsa_keygen_en_msg__field_indices_by_name,
  1,  eddsa_keygen_en_msg__number_ranges,
  (ProtobufCMessageInit) eddsa_keygen_en_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor eddsa_free_key_msg__field_descriptors[1] =
{
  {
    "privkey",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EddsaFreeKeyMsg, privkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eddsa_free_key_msg__field_indices_by_name[] = {
  0,   /* field[0] = privkey */
};
static const ProtobufCIntRange eddsa_free_key_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor eddsa_free_key_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EddsaFreeKeyMsg",
  "EddsaFreeKeyMsg",
  "EddsaFreeKeyMsg",
  "",
  sizeof(EddsaFreeKeyMsg),
  1,
  eddsa_free_key_msg__field_descriptors,
  eddsa_free_key_msg__field_indices_by_name,
  1,  eddsa_free_key_msg__number_ranges,
  (ProtobufCMessageInit) eddsa_free_key_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
