/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/hmac.proto */

#ifndef PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fhmac_2eproto__INCLUDED
#define PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fhmac_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct HmacDataMsg HmacDataMsg;


/* --- enums --- */


/* --- messages --- */

struct  HmacDataMsg
{
  ProtobufCMessage base;
  ProtobufCBinaryData key;
  ProtobufCBinaryData msg;
  uint32_t maclen;
  ProtobufCBinaryData mac;
  uint64_t cipher;
};
#define HMAC_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hmac_data_msg__descriptor) \
, {0,NULL}, {0,NULL}, 0, {0,NULL}, 0 }


/* HmacDataMsg methods */
void   hmac_data_msg__init
                     (HmacDataMsg         *message);
size_t hmac_data_msg__get_packed_size
                     (const HmacDataMsg   *message);
size_t hmac_data_msg__pack
                     (const HmacDataMsg   *message,
                      uint8_t             *out);
size_t hmac_data_msg__pack_to_buffer
                     (const HmacDataMsg   *message,
                      ProtobufCBuffer     *buffer);
HmacDataMsg *
       hmac_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hmac_data_msg__free_unpacked
                     (HmacDataMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*HmacDataMsg_Closure)
                 (const HmacDataMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hmac_data_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fhmac_2eproto__INCLUDED */
