/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/hmac.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/hmac.pb-c.h"
void   hmac_data_msg__init
                     (HmacDataMsg         *message)
{
  static const HmacDataMsg init_value = HMAC_DATA_MSG__INIT;
  *message = init_value;
}
size_t hmac_data_msg__get_packed_size
                     (const HmacDataMsg *message)
{
  assert(message->base.descriptor == &hmac_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hmac_data_msg__pack
                     (const HmacDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hmac_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hmac_data_msg__pack_to_buffer
                     (const HmacDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hmac_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HmacDataMsg *
       hmac_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HmacDataMsg *)
     protobuf_c_message_unpack (&hmac_data_msg__descriptor,
                                allocator, len, data);
}
void   hmac_data_msg__free_unpacked
                     (HmacDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hmac_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hmac_data_msg__field_descriptors[5] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HmacDataMsg, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HmacDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maclen",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(HmacDataMsg, maclen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HmacDataMsg, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(HmacDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hmac_data_msg__field_indices_by_name[] = {
  4,   /* field[4] = cipher */
  0,   /* field[0] = key */
  3,   /* field[3] = mac */
  2,   /* field[2] = maclen */
  1,   /* field[1] = msg */
};
static const ProtobufCIntRange hmac_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor hmac_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HmacDataMsg",
  "HmacDataMsg",
  "HmacDataMsg",
  "",
  sizeof(HmacDataMsg),
  5,
  hmac_data_msg__field_descriptors,
  hmac_data_msg__field_indices_by_name,
  1,  hmac_data_msg__number_ranges,
  (ProtobufCMessageInit) hmac_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
