/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/kbkdf.proto */

#ifndef PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fkbkdf_2eproto__INCLUDED
#define PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fkbkdf_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Kdf108DataMsg Kdf108DataMsg;
typedef struct Kdf108KmacDataMsg Kdf108KmacDataMsg;


/* --- enums --- */


/* --- messages --- */

struct  Kdf108DataMsg
{
  ProtobufCMessage base;
  uint64_t mac;
  uint64_t kdfmode;
  uint64_t counter_location;
  uint32_t counter_length;
  uint32_t derived_key_length;
  ProtobufCBinaryData key;
  ProtobufCBinaryData iv;
  ProtobufCBinaryData context;
  ProtobufCBinaryData label;
  uint32_t break_location;
  ProtobufCBinaryData fixed_data;
  ProtobufCBinaryData derived_key;
};
#define KDF108_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kdf108_data_msg__descriptor) \
, 0, 0, 0, 0, 0, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, 0, {0,NULL}, {0,NULL} }


struct  Kdf108KmacDataMsg
{
  ProtobufCMessage base;
  uint64_t mac;
  uint32_t derived_key_length;
  ProtobufCBinaryData key;
  ProtobufCBinaryData context;
  ProtobufCBinaryData label;
  ProtobufCBinaryData derived_key;
};
#define KDF108_KMAC_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kdf108_kmac_data_msg__descriptor) \
, 0, 0, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL} }


/* Kdf108DataMsg methods */
void   kdf108_data_msg__init
                     (Kdf108DataMsg         *message);
size_t kdf108_data_msg__get_packed_size
                     (const Kdf108DataMsg   *message);
size_t kdf108_data_msg__pack
                     (const Kdf108DataMsg   *message,
                      uint8_t             *out);
size_t kdf108_data_msg__pack_to_buffer
                     (const Kdf108DataMsg   *message,
                      ProtobufCBuffer     *buffer);
Kdf108DataMsg *
       kdf108_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kdf108_data_msg__free_unpacked
                     (Kdf108DataMsg *message,
                      ProtobufCAllocator *allocator);
/* Kdf108KmacDataMsg methods */
void   kdf108_kmac_data_msg__init
                     (Kdf108KmacDataMsg         *message);
size_t kdf108_kmac_data_msg__get_packed_size
                     (const Kdf108KmacDataMsg   *message);
size_t kdf108_kmac_data_msg__pack
                     (const Kdf108KmacDataMsg   *message,
                      uint8_t             *out);
size_t kdf108_kmac_data_msg__pack_to_buffer
                     (const Kdf108KmacDataMsg   *message,
                      ProtobufCBuffer     *buffer);
Kdf108KmacDataMsg *
       kdf108_kmac_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kdf108_kmac_data_msg__free_unpacked
                     (Kdf108KmacDataMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Kdf108DataMsg_Closure)
                 (const Kdf108DataMsg *message,
                  void *closure_data);
typedef void (*Kdf108KmacDataMsg_Closure)
                 (const Kdf108KmacDataMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor kdf108_data_msg__descriptor;
extern const ProtobufCMessageDescriptor kdf108_kmac_data_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fkbkdf_2eproto__INCLUDED */
