/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/kbkdf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/kbkdf.pb-c.h"
void   kdf108_data_msg__init
                     (Kdf108DataMsg         *message)
{
  static const Kdf108DataMsg init_value = KDF108_DATA_MSG__INIT;
  *message = init_value;
}
size_t kdf108_data_msg__get_packed_size
                     (const Kdf108DataMsg *message)
{
  assert(message->base.descriptor == &kdf108_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kdf108_data_msg__pack
                     (const Kdf108DataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kdf108_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kdf108_data_msg__pack_to_buffer
                     (const Kdf108DataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kdf108_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kdf108DataMsg *
       kdf108_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kdf108DataMsg *)
     protobuf_c_message_unpack (&kdf108_data_msg__descriptor,
                                allocator, len, data);
}
void   kdf108_data_msg__free_unpacked
                     (Kdf108DataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kdf108_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kdf108_kmac_data_msg__init
                     (Kdf108KmacDataMsg         *message)
{
  static const Kdf108KmacDataMsg init_value = KDF108_KMAC_DATA_MSG__INIT;
  *message = init_value;
}
size_t kdf108_kmac_data_msg__get_packed_size
                     (const Kdf108KmacDataMsg *message)
{
  assert(message->base.descriptor == &kdf108_kmac_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kdf108_kmac_data_msg__pack
                     (const Kdf108KmacDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kdf108_kmac_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kdf108_kmac_data_msg__pack_to_buffer
                     (const Kdf108KmacDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kdf108_kmac_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kdf108KmacDataMsg *
       kdf108_kmac_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kdf108KmacDataMsg *)
     protobuf_c_message_unpack (&kdf108_kmac_data_msg__descriptor,
                                allocator, len, data);
}
void   kdf108_kmac_data_msg__free_unpacked
                     (Kdf108KmacDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kdf108_kmac_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor kdf108_data_msg__field_descriptors[12] =
{
  {
    "mac",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kdfmode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, kdfmode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counter_location",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, counter_location),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counter_length",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, counter_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_key_length",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, derived_key_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iv",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, iv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, context),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, label),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "break_location",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, break_location),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixed_data",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, fixed_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_key",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kdf108DataMsg, derived_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kdf108_data_msg__field_indices_by_name[] = {
  9,   /* field[9] = break_location */
  7,   /* field[7] = context */
  3,   /* field[3] = counter_length */
  2,   /* field[2] = counter_location */
  11,   /* field[11] = derived_key */
  4,   /* field[4] = derived_key_length */
  10,   /* field[10] = fixed_data */
  6,   /* field[6] = iv */
  1,   /* field[1] = kdfmode */
  5,   /* field[5] = key */
  8,   /* field[8] = label */
  0,   /* field[0] = mac */
};
static const ProtobufCIntRange kdf108_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor kdf108_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Kdf108DataMsg",
  "Kdf108DataMsg",
  "Kdf108DataMsg",
  "",
  sizeof(Kdf108DataMsg),
  12,
  kdf108_data_msg__field_descriptors,
  kdf108_data_msg__field_indices_by_name,
  1,  kdf108_data_msg__number_ranges,
  (ProtobufCMessageInit) kdf108_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kdf108_kmac_data_msg__field_descriptors[6] =
{
  {
    "mac",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Kdf108KmacDataMsg, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_key_length",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Kdf108KmacDataMsg, derived_key_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kdf108KmacDataMsg, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kdf108KmacDataMsg, context),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kdf108KmacDataMsg, label),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_key",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kdf108KmacDataMsg, derived_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kdf108_kmac_data_msg__field_indices_by_name[] = {
  3,   /* field[3] = context */
  5,   /* field[5] = derived_key */
  1,   /* field[1] = derived_key_length */
  2,   /* field[2] = key */
  4,   /* field[4] = label */
  0,   /* field[0] = mac */
};
static const ProtobufCIntRange kdf108_kmac_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor kdf108_kmac_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Kdf108KmacDataMsg",
  "Kdf108KmacDataMsg",
  "Kdf108KmacDataMsg",
  "",
  sizeof(Kdf108KmacDataMsg),
  6,
  kdf108_kmac_data_msg__field_descriptors,
  kdf108_kmac_data_msg__field_indices_by_name,
  1,  kdf108_kmac_data_msg__number_ranges,
  (ProtobufCMessageInit) kdf108_kmac_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
