/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/kda_hkdf.proto */

#ifndef PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fkda_5fhkdf_2eproto__INCLUDED
#define PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fkda_5fhkdf_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct HkdfDataMsg HkdfDataMsg;


/* --- enums --- */


/* --- messages --- */

struct  HkdfDataMsg
{
  ProtobufCMessage base;
  uint64_t hash;
  uint32_t dkmlen;
  ProtobufCBinaryData salt;
  ProtobufCBinaryData z;
  ProtobufCBinaryData t;
  ProtobufCBinaryData info;
  ProtobufCBinaryData dkm;
  uint32_t validity_success;
};
#define HKDF_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hkdf_data_msg__descriptor) \
, 0, 0, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, 0 }


/* HkdfDataMsg methods */
void   hkdf_data_msg__init
                     (HkdfDataMsg         *message);
size_t hkdf_data_msg__get_packed_size
                     (const HkdfDataMsg   *message);
size_t hkdf_data_msg__pack
                     (const HkdfDataMsg   *message,
                      uint8_t             *out);
size_t hkdf_data_msg__pack_to_buffer
                     (const HkdfDataMsg   *message,
                      ProtobufCBuffer     *buffer);
HkdfDataMsg *
       hkdf_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hkdf_data_msg__free_unpacked
                     (HkdfDataMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*HkdfDataMsg_Closure)
                 (const HkdfDataMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hkdf_data_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fkda_5fhkdf_2eproto__INCLUDED */
