/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/kda_hkdf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/kda_hkdf.pb-c.h"
void   hkdf_data_msg__init
                     (HkdfDataMsg         *message)
{
  static const HkdfDataMsg init_value = HKDF_DATA_MSG__INIT;
  *message = init_value;
}
size_t hkdf_data_msg__get_packed_size
                     (const HkdfDataMsg *message)
{
  assert(message->base.descriptor == &hkdf_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hkdf_data_msg__pack
                     (const HkdfDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hkdf_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hkdf_data_msg__pack_to_buffer
                     (const HkdfDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hkdf_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HkdfDataMsg *
       hkdf_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HkdfDataMsg *)
     protobuf_c_message_unpack (&hkdf_data_msg__descriptor,
                                allocator, len, data);
}
void   hkdf_data_msg__free_unpacked
                     (HkdfDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hkdf_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hkdf_data_msg__field_descriptors[8] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(HkdfDataMsg, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dkmlen",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(HkdfDataMsg, dkmlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "salt",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HkdfDataMsg, salt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HkdfDataMsg, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HkdfDataMsg, t),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HkdfDataMsg, info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dkm",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HkdfDataMsg, dkm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "validity_success",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(HkdfDataMsg, validity_success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hkdf_data_msg__field_indices_by_name[] = {
  6,   /* field[6] = dkm */
  1,   /* field[1] = dkmlen */
  0,   /* field[0] = hash */
  5,   /* field[5] = info */
  2,   /* field[2] = salt */
  4,   /* field[4] = t */
  7,   /* field[7] = validity_success */
  3,   /* field[3] = z */
};
static const ProtobufCIntRange hkdf_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor hkdf_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HkdfDataMsg",
  "HkdfDataMsg",
  "HkdfDataMsg",
  "",
  sizeof(HkdfDataMsg),
  8,
  hkdf_data_msg__field_descriptors,
  hkdf_data_msg__field_indices_by_name,
  1,  hkdf_data_msg__number_ranges,
  (ProtobufCMessageInit) hkdf_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
