/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/kmac.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/kmac.pb-c.h"
void   kmac_data_msg__init
                     (KmacDataMsg         *message)
{
  static const KmacDataMsg init_value = KMAC_DATA_MSG__INIT;
  *message = init_value;
}
size_t kmac_data_msg__get_packed_size
                     (const KmacDataMsg *message)
{
  assert(message->base.descriptor == &kmac_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kmac_data_msg__pack
                     (const KmacDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kmac_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kmac_data_msg__pack_to_buffer
                     (const KmacDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kmac_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KmacDataMsg *
       kmac_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KmacDataMsg *)
     protobuf_c_message_unpack (&kmac_data_msg__descriptor,
                                allocator, len, data);
}
void   kmac_data_msg__free_unpacked
                     (KmacDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kmac_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor kmac_data_msg__field_descriptors[9] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(KmacDataMsg, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(KmacDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maclen",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(KmacDataMsg, maclen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keylen",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(KmacDataMsg, keylen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(KmacDataMsg, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "customization",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(KmacDataMsg, customization),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "verify_result",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(KmacDataMsg, verify_result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xof_enabled",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(KmacDataMsg, xof_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(KmacDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kmac_data_msg__field_indices_by_name[] = {
  8,   /* field[8] = cipher */
  5,   /* field[5] = customization */
  0,   /* field[0] = key */
  3,   /* field[3] = keylen */
  4,   /* field[4] = mac */
  2,   /* field[2] = maclen */
  1,   /* field[1] = msg */
  6,   /* field[6] = verify_result */
  7,   /* field[7] = xof_enabled */
};
static const ProtobufCIntRange kmac_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor kmac_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KmacDataMsg",
  "KmacDataMsg",
  "KmacDataMsg",
  "",
  sizeof(KmacDataMsg),
  9,
  kmac_data_msg__field_descriptors,
  kmac_data_msg__field_indices_by_name,
  1,  kmac_data_msg__number_ranges,
  (ProtobufCMessageInit) kmac_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
