/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/ml-dsa.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/ml-dsa.pb-c.h"
void   ml_dsa_keygen_data_msg__init
                     (MlDsaKeygenDataMsg         *message)
{
  static const MlDsaKeygenDataMsg init_value = ML_DSA_KEYGEN_DATA_MSG__INIT;
  *message = init_value;
}
size_t ml_dsa_keygen_data_msg__get_packed_size
                     (const MlDsaKeygenDataMsg *message)
{
  assert(message->base.descriptor == &ml_dsa_keygen_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ml_dsa_keygen_data_msg__pack
                     (const MlDsaKeygenDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ml_dsa_keygen_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ml_dsa_keygen_data_msg__pack_to_buffer
                     (const MlDsaKeygenDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ml_dsa_keygen_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MlDsaKeygenDataMsg *
       ml_dsa_keygen_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MlDsaKeygenDataMsg *)
     protobuf_c_message_unpack (&ml_dsa_keygen_data_msg__descriptor,
                                allocator, len, data);
}
void   ml_dsa_keygen_data_msg__free_unpacked
                     (MlDsaKeygenDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ml_dsa_keygen_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ml_dsa_siggen_data_msg__init
                     (MlDsaSiggenDataMsg         *message)
{
  static const MlDsaSiggenDataMsg init_value = ML_DSA_SIGGEN_DATA_MSG__INIT;
  *message = init_value;
}
size_t ml_dsa_siggen_data_msg__get_packed_size
                     (const MlDsaSiggenDataMsg *message)
{
  assert(message->base.descriptor == &ml_dsa_siggen_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ml_dsa_siggen_data_msg__pack
                     (const MlDsaSiggenDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ml_dsa_siggen_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ml_dsa_siggen_data_msg__pack_to_buffer
                     (const MlDsaSiggenDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ml_dsa_siggen_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MlDsaSiggenDataMsg *
       ml_dsa_siggen_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MlDsaSiggenDataMsg *)
     protobuf_c_message_unpack (&ml_dsa_siggen_data_msg__descriptor,
                                allocator, len, data);
}
void   ml_dsa_siggen_data_msg__free_unpacked
                     (MlDsaSiggenDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ml_dsa_siggen_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ml_dsa_sigver_data_msg__init
                     (MlDsaSigverDataMsg         *message)
{
  static const MlDsaSigverDataMsg init_value = ML_DSA_SIGVER_DATA_MSG__INIT;
  *message = init_value;
}
size_t ml_dsa_sigver_data_msg__get_packed_size
                     (const MlDsaSigverDataMsg *message)
{
  assert(message->base.descriptor == &ml_dsa_sigver_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ml_dsa_sigver_data_msg__pack
                     (const MlDsaSigverDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ml_dsa_sigver_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ml_dsa_sigver_data_msg__pack_to_buffer
                     (const MlDsaSigverDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ml_dsa_sigver_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MlDsaSigverDataMsg *
       ml_dsa_sigver_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MlDsaSigverDataMsg *)
     protobuf_c_message_unpack (&ml_dsa_sigver_data_msg__descriptor,
                                allocator, len, data);
}
void   ml_dsa_sigver_data_msg__free_unpacked
                     (MlDsaSigverDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ml_dsa_sigver_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ml_dsa_keygen_en_msg__init
                     (MlDsaKeygenEnMsg         *message)
{
  static const MlDsaKeygenEnMsg init_value = ML_DSA_KEYGEN_EN_MSG__INIT;
  *message = init_value;
}
size_t ml_dsa_keygen_en_msg__get_packed_size
                     (const MlDsaKeygenEnMsg *message)
{
  assert(message->base.descriptor == &ml_dsa_keygen_en_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ml_dsa_keygen_en_msg__pack
                     (const MlDsaKeygenEnMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ml_dsa_keygen_en_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ml_dsa_keygen_en_msg__pack_to_buffer
                     (const MlDsaKeygenEnMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ml_dsa_keygen_en_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MlDsaKeygenEnMsg *
       ml_dsa_keygen_en_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MlDsaKeygenEnMsg *)
     protobuf_c_message_unpack (&ml_dsa_keygen_en_msg__descriptor,
                                allocator, len, data);
}
void   ml_dsa_keygen_en_msg__free_unpacked
                     (MlDsaKeygenEnMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ml_dsa_keygen_en_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ml_dsa_free_key_msg__init
                     (MlDsaFreeKeyMsg         *message)
{
  static const MlDsaFreeKeyMsg init_value = ML_DSA_FREE_KEY_MSG__INIT;
  *message = init_value;
}
size_t ml_dsa_free_key_msg__get_packed_size
                     (const MlDsaFreeKeyMsg *message)
{
  assert(message->base.descriptor == &ml_dsa_free_key_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ml_dsa_free_key_msg__pack
                     (const MlDsaFreeKeyMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ml_dsa_free_key_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ml_dsa_free_key_msg__pack_to_buffer
                     (const MlDsaFreeKeyMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ml_dsa_free_key_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MlDsaFreeKeyMsg *
       ml_dsa_free_key_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MlDsaFreeKeyMsg *)
     protobuf_c_message_unpack (&ml_dsa_free_key_msg__descriptor,
                                allocator, len, data);
}
void   ml_dsa_free_key_msg__free_unpacked
                     (MlDsaFreeKeyMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ml_dsa_free_key_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ml_dsa_keygen_data_msg__field_descriptors[4] =
{
  {
    "seed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaKeygenDataMsg, seed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pk",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaKeygenDataMsg, pk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sk",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaKeygenDataMsg, sk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MlDsaKeygenDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ml_dsa_keygen_data_msg__field_indices_by_name[] = {
  3,   /* field[3] = cipher */
  1,   /* field[1] = pk */
  0,   /* field[0] = seed */
  2,   /* field[2] = sk */
};
static const ProtobufCIntRange ml_dsa_keygen_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ml_dsa_keygen_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MlDsaKeygenDataMsg",
  "MlDsaKeygenDataMsg",
  "MlDsaKeygenDataMsg",
  "",
  sizeof(MlDsaKeygenDataMsg),
  4,
  ml_dsa_keygen_data_msg__field_descriptors,
  ml_dsa_keygen_data_msg__field_indices_by_name,
  1,  ml_dsa_keygen_data_msg__number_ranges,
  (ProtobufCMessageInit) ml_dsa_keygen_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ml_dsa_siggen_data_msg__field_descriptors[10] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSiggenDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sig",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSiggenDataMsg, sig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pk",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSiggenDataMsg, pk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rnd",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSiggenDataMsg, rnd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sk",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSiggenDataMsg, sk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSiggenDataMsg, context),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSiggenDataMsg, interface),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "privkey",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MlDsaSiggenDataMsg, privkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MlDsaSiggenDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hashalg",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MlDsaSiggenDataMsg, hashalg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ml_dsa_siggen_data_msg__field_indices_by_name[] = {
  8,   /* field[8] = cipher */
  5,   /* field[5] = context */
  9,   /* field[9] = hashalg */
  6,   /* field[6] = interface */
  0,   /* field[0] = msg */
  2,   /* field[2] = pk */
  7,   /* field[7] = privkey */
  3,   /* field[3] = rnd */
  1,   /* field[1] = sig */
  4,   /* field[4] = sk */
};
static const ProtobufCIntRange ml_dsa_siggen_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor ml_dsa_siggen_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MlDsaSiggenDataMsg",
  "MlDsaSiggenDataMsg",
  "MlDsaSiggenDataMsg",
  "",
  sizeof(MlDsaSiggenDataMsg),
  10,
  ml_dsa_siggen_data_msg__field_descriptors,
  ml_dsa_siggen_data_msg__field_indices_by_name,
  1,  ml_dsa_siggen_data_msg__number_ranges,
  (ProtobufCMessageInit) ml_dsa_siggen_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ml_dsa_sigver_data_msg__field_descriptors[8] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSigverDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sig",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSigverDataMsg, sig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pk",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSigverDataMsg, pk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSigverDataMsg, context),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaSigverDataMsg, interface),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MlDsaSigverDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hashalg",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MlDsaSigverDataMsg, hashalg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sigver_success",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MlDsaSigverDataMsg, sigver_success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ml_dsa_sigver_data_msg__field_indices_by_name[] = {
  5,   /* field[5] = cipher */
  3,   /* field[3] = context */
  6,   /* field[6] = hashalg */
  4,   /* field[4] = interface */
  0,   /* field[0] = msg */
  2,   /* field[2] = pk */
  1,   /* field[1] = sig */
  7,   /* field[7] = sigver_success */
};
static const ProtobufCIntRange ml_dsa_sigver_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ml_dsa_sigver_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MlDsaSigverDataMsg",
  "MlDsaSigverDataMsg",
  "MlDsaSigverDataMsg",
  "",
  sizeof(MlDsaSigverDataMsg),
  8,
  ml_dsa_sigver_data_msg__field_descriptors,
  ml_dsa_sigver_data_msg__field_indices_by_name,
  1,  ml_dsa_sigver_data_msg__number_ranges,
  (ProtobufCMessageInit) ml_dsa_sigver_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ml_dsa_keygen_en_msg__field_descriptors[3] =
{
  {
    "cipher",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MlDsaKeygenEnMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pk",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlDsaKeygenEnMsg, pk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "privkey",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MlDsaKeygenEnMsg, privkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ml_dsa_keygen_en_msg__field_indices_by_name[] = {
  0,   /* field[0] = cipher */
  1,   /* field[1] = pk */
  2,   /* field[2] = privkey */
};
static const ProtobufCIntRange ml_dsa_keygen_en_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ml_dsa_keygen_en_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MlDsaKeygenEnMsg",
  "MlDsaKeygenEnMsg",
  "MlDsaKeygenEnMsg",
  "",
  sizeof(MlDsaKeygenEnMsg),
  3,
  ml_dsa_keygen_en_msg__field_descriptors,
  ml_dsa_keygen_en_msg__field_indices_by_name,
  1,  ml_dsa_keygen_en_msg__number_ranges,
  (ProtobufCMessageInit) ml_dsa_keygen_en_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ml_dsa_free_key_msg__field_descriptors[1] =
{
  {
    "privkey",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MlDsaFreeKeyMsg, privkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ml_dsa_free_key_msg__field_indices_by_name[] = {
  0,   /* field[0] = privkey */
};
static const ProtobufCIntRange ml_dsa_free_key_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ml_dsa_free_key_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MlDsaFreeKeyMsg",
  "MlDsaFreeKeyMsg",
  "MlDsaFreeKeyMsg",
  "",
  sizeof(MlDsaFreeKeyMsg),
  1,
  ml_dsa_free_key_msg__field_descriptors,
  ml_dsa_free_key_msg__field_indices_by_name,
  1,  ml_dsa_free_key_msg__number_ranges,
  (ProtobufCMessageInit) ml_dsa_free_key_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
