/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/ml-kem.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/ml-kem.pb-c.h"
void   ml_kem_keygen_data_msg__init
                     (MlKemKeygenDataMsg         *message)
{
  static const MlKemKeygenDataMsg init_value = ML_KEM_KEYGEN_DATA_MSG__INIT;
  *message = init_value;
}
size_t ml_kem_keygen_data_msg__get_packed_size
                     (const MlKemKeygenDataMsg *message)
{
  assert(message->base.descriptor == &ml_kem_keygen_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ml_kem_keygen_data_msg__pack
                     (const MlKemKeygenDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ml_kem_keygen_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ml_kem_keygen_data_msg__pack_to_buffer
                     (const MlKemKeygenDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ml_kem_keygen_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MlKemKeygenDataMsg *
       ml_kem_keygen_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MlKemKeygenDataMsg *)
     protobuf_c_message_unpack (&ml_kem_keygen_data_msg__descriptor,
                                allocator, len, data);
}
void   ml_kem_keygen_data_msg__free_unpacked
                     (MlKemKeygenDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ml_kem_keygen_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ml_kem_encap_data_msg__init
                     (MlKemEncapDataMsg         *message)
{
  static const MlKemEncapDataMsg init_value = ML_KEM_ENCAP_DATA_MSG__INIT;
  *message = init_value;
}
size_t ml_kem_encap_data_msg__get_packed_size
                     (const MlKemEncapDataMsg *message)
{
  assert(message->base.descriptor == &ml_kem_encap_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ml_kem_encap_data_msg__pack
                     (const MlKemEncapDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ml_kem_encap_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ml_kem_encap_data_msg__pack_to_buffer
                     (const MlKemEncapDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ml_kem_encap_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MlKemEncapDataMsg *
       ml_kem_encap_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MlKemEncapDataMsg *)
     protobuf_c_message_unpack (&ml_kem_encap_data_msg__descriptor,
                                allocator, len, data);
}
void   ml_kem_encap_data_msg__free_unpacked
                     (MlKemEncapDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ml_kem_encap_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ml_kem_decap_data_msg__init
                     (MlKemDecapDataMsg         *message)
{
  static const MlKemDecapDataMsg init_value = ML_KEM_DECAP_DATA_MSG__INIT;
  *message = init_value;
}
size_t ml_kem_decap_data_msg__get_packed_size
                     (const MlKemDecapDataMsg *message)
{
  assert(message->base.descriptor == &ml_kem_decap_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ml_kem_decap_data_msg__pack
                     (const MlKemDecapDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ml_kem_decap_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ml_kem_decap_data_msg__pack_to_buffer
                     (const MlKemDecapDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ml_kem_decap_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MlKemDecapDataMsg *
       ml_kem_decap_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MlKemDecapDataMsg *)
     protobuf_c_message_unpack (&ml_kem_decap_data_msg__descriptor,
                                allocator, len, data);
}
void   ml_kem_decap_data_msg__free_unpacked
                     (MlKemDecapDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ml_kem_decap_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ml_kem_keygen_data_msg__field_descriptors[5] =
{
  {
    "d",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemKeygenDataMsg, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemKeygenDataMsg, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ek",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemKeygenDataMsg, ek),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dk",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemKeygenDataMsg, dk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MlKemKeygenDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ml_kem_keygen_data_msg__field_indices_by_name[] = {
  4,   /* field[4] = cipher */
  0,   /* field[0] = d */
  3,   /* field[3] = dk */
  2,   /* field[2] = ek */
  1,   /* field[1] = z */
};
static const ProtobufCIntRange ml_kem_keygen_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ml_kem_keygen_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MlKemKeygenDataMsg",
  "MlKemKeygenDataMsg",
  "MlKemKeygenDataMsg",
  "",
  sizeof(MlKemKeygenDataMsg),
  5,
  ml_kem_keygen_data_msg__field_descriptors,
  ml_kem_keygen_data_msg__field_indices_by_name,
  1,  ml_kem_keygen_data_msg__number_ranges,
  (ProtobufCMessageInit) ml_kem_keygen_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ml_kem_encap_data_msg__field_descriptors[5] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemEncapDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ek",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemEncapDataMsg, ek),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemEncapDataMsg, c),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ss",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemEncapDataMsg, ss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MlKemEncapDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ml_kem_encap_data_msg__field_indices_by_name[] = {
  2,   /* field[2] = c */
  4,   /* field[4] = cipher */
  1,   /* field[1] = ek */
  0,   /* field[0] = msg */
  3,   /* field[3] = ss */
};
static const ProtobufCIntRange ml_kem_encap_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ml_kem_encap_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MlKemEncapDataMsg",
  "MlKemEncapDataMsg",
  "MlKemEncapDataMsg",
  "",
  sizeof(MlKemEncapDataMsg),
  5,
  ml_kem_encap_data_msg__field_descriptors,
  ml_kem_encap_data_msg__field_indices_by_name,
  1,  ml_kem_encap_data_msg__number_ranges,
  (ProtobufCMessageInit) ml_kem_encap_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ml_kem_decap_data_msg__field_descriptors[4] =
{
  {
    "c",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemDecapDataMsg, c),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dk",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemDecapDataMsg, dk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ss",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MlKemDecapDataMsg, ss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MlKemDecapDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ml_kem_decap_data_msg__field_indices_by_name[] = {
  0,   /* field[0] = c */
  3,   /* field[3] = cipher */
  1,   /* field[1] = dk */
  2,   /* field[2] = ss */
};
static const ProtobufCIntRange ml_kem_decap_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ml_kem_decap_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MlKemDecapDataMsg",
  "MlKemDecapDataMsg",
  "MlKemDecapDataMsg",
  "",
  sizeof(MlKemDecapDataMsg),
  4,
  ml_kem_decap_data_msg__field_descriptors,
  ml_kem_decap_data_msg__field_indices_by_name,
  1,  ml_kem_decap_data_msg__number_ranges,
  (ProtobufCMessageInit) ml_kem_decap_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
