/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/pbkdf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/pbkdf.pb-c.h"
void   pbkdf_data_msg__init
                     (PbkdfDataMsg         *message)
{
  static const PbkdfDataMsg init_value = PBKDF_DATA_MSG__INIT;
  *message = init_value;
}
size_t pbkdf_data_msg__get_packed_size
                     (const PbkdfDataMsg *message)
{
  assert(message->base.descriptor == &pbkdf_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbkdf_data_msg__pack
                     (const PbkdfDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbkdf_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbkdf_data_msg__pack_to_buffer
                     (const PbkdfDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbkdf_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbkdfDataMsg *
       pbkdf_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbkdfDataMsg *)
     protobuf_c_message_unpack (&pbkdf_data_msg__descriptor,
                                allocator, len, data);
}
void   pbkdf_data_msg__free_unpacked
                     (PbkdfDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbkdf_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pbkdf_data_msg__field_descriptors[6] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PbkdfDataMsg, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_key_length",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbkdfDataMsg, derived_key_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iteration_count",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbkdfDataMsg, iteration_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PbkdfDataMsg, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "salt",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PbkdfDataMsg, salt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_key",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PbkdfDataMsg, derived_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbkdf_data_msg__field_indices_by_name[] = {
  5,   /* field[5] = derived_key */
  1,   /* field[1] = derived_key_length */
  0,   /* field[0] = hash */
  2,   /* field[2] = iteration_count */
  3,   /* field[3] = password */
  4,   /* field[4] = salt */
};
static const ProtobufCIntRange pbkdf_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor pbkdf_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PbkdfDataMsg",
  "PbkdfDataMsg",
  "PbkdfDataMsg",
  "",
  sizeof(PbkdfDataMsg),
  6,
  pbkdf_data_msg__field_descriptors,
  pbkdf_data_msg__field_indices_by_name,
  1,  pbkdf_data_msg__number_ranges,
  (ProtobufCMessageInit) pbkdf_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
