/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/pbkdf.proto */

#ifndef PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fpbkdf_2eproto__INCLUDED
#define PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fpbkdf_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct PbkdfDataMsg PbkdfDataMsg;


/* --- enums --- */


/* --- messages --- */

struct  PbkdfDataMsg
{
  ProtobufCMessage base;
  uint64_t hash;
  uint32_t derived_key_length;
  uint32_t iteration_count;
  ProtobufCBinaryData password;
  ProtobufCBinaryData salt;
  ProtobufCBinaryData derived_key;
};
#define PBKDF_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pbkdf_data_msg__descriptor) \
, 0, 0, 0, {0,NULL}, {0,NULL}, {0,NULL} }


/* PbkdfDataMsg methods */
void   pbkdf_data_msg__init
                     (PbkdfDataMsg         *message);
size_t pbkdf_data_msg__get_packed_size
                     (const PbkdfDataMsg   *message);
size_t pbkdf_data_msg__pack
                     (const PbkdfDataMsg   *message,
                      uint8_t             *out);
size_t pbkdf_data_msg__pack_to_buffer
                     (const PbkdfDataMsg   *message,
                      ProtobufCBuffer     *buffer);
PbkdfDataMsg *
       pbkdf_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pbkdf_data_msg__free_unpacked
                     (PbkdfDataMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PbkdfDataMsg_Closure)
                 (const PbkdfDataMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pbkdf_data_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fpbkdf_2eproto__INCLUDED */
