/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/rsa.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/rsa.pb-c.h"
void   rsa_keygen_prime_data_msg__init
                     (RsaKeygenPrimeDataMsg         *message)
{
  static const RsaKeygenPrimeDataMsg init_value = RSA_KEYGEN_PRIME_DATA_MSG__INIT;
  *message = init_value;
}
size_t rsa_keygen_prime_data_msg__get_packed_size
                     (const RsaKeygenPrimeDataMsg *message)
{
  assert(message->base.descriptor == &rsa_keygen_prime_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_keygen_prime_data_msg__pack
                     (const RsaKeygenPrimeDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_keygen_prime_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_keygen_prime_data_msg__pack_to_buffer
                     (const RsaKeygenPrimeDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_keygen_prime_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaKeygenPrimeDataMsg *
       rsa_keygen_prime_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaKeygenPrimeDataMsg *)
     protobuf_c_message_unpack (&rsa_keygen_prime_data_msg__descriptor,
                                allocator, len, data);
}
void   rsa_keygen_prime_data_msg__free_unpacked
                     (RsaKeygenPrimeDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rsa_keygen_prime_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsa_keygen_data_msg__init
                     (RsaKeygenDataMsg         *message)
{
  static const RsaKeygenDataMsg init_value = RSA_KEYGEN_DATA_MSG__INIT;
  *message = init_value;
}
size_t rsa_keygen_data_msg__get_packed_size
                     (const RsaKeygenDataMsg *message)
{
  assert(message->base.descriptor == &rsa_keygen_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_keygen_data_msg__pack
                     (const RsaKeygenDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_keygen_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_keygen_data_msg__pack_to_buffer
                     (const RsaKeygenDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_keygen_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaKeygenDataMsg *
       rsa_keygen_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaKeygenDataMsg *)
     protobuf_c_message_unpack (&rsa_keygen_data_msg__descriptor,
                                allocator, len, data);
}
void   rsa_keygen_data_msg__free_unpacked
                     (RsaKeygenDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rsa_keygen_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsa_keygen_prov_prime_data_msg__init
                     (RsaKeygenProvPrimeDataMsg         *message)
{
  static const RsaKeygenProvPrimeDataMsg init_value = RSA_KEYGEN_PROV_PRIME_DATA_MSG__INIT;
  *message = init_value;
}
size_t rsa_keygen_prov_prime_data_msg__get_packed_size
                     (const RsaKeygenProvPrimeDataMsg *message)
{
  assert(message->base.descriptor == &rsa_keygen_prov_prime_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_keygen_prov_prime_data_msg__pack
                     (const RsaKeygenProvPrimeDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_keygen_prov_prime_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_keygen_prov_prime_data_msg__pack_to_buffer
                     (const RsaKeygenProvPrimeDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_keygen_prov_prime_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaKeygenProvPrimeDataMsg *
       rsa_keygen_prov_prime_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaKeygenProvPrimeDataMsg *)
     protobuf_c_message_unpack (&rsa_keygen_prov_prime_data_msg__descriptor,
                                allocator, len, data);
}
void   rsa_keygen_prov_prime_data_msg__free_unpacked
                     (RsaKeygenProvPrimeDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rsa_keygen_prov_prime_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsa_siggen_data_msg__init
                     (RsaSiggenDataMsg         *message)
{
  static const RsaSiggenDataMsg init_value = RSA_SIGGEN_DATA_MSG__INIT;
  *message = init_value;
}
size_t rsa_siggen_data_msg__get_packed_size
                     (const RsaSiggenDataMsg *message)
{
  assert(message->base.descriptor == &rsa_siggen_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_siggen_data_msg__pack
                     (const RsaSiggenDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_siggen_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_siggen_data_msg__pack_to_buffer
                     (const RsaSiggenDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_siggen_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaSiggenDataMsg *
       rsa_siggen_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaSiggenDataMsg *)
     protobuf_c_message_unpack (&rsa_siggen_data_msg__descriptor,
                                allocator, len, data);
}
void   rsa_siggen_data_msg__free_unpacked
                     (RsaSiggenDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rsa_siggen_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsa_sigver_data_msg__init
                     (RsaSigverDataMsg         *message)
{
  static const RsaSigverDataMsg init_value = RSA_SIGVER_DATA_MSG__INIT;
  *message = init_value;
}
size_t rsa_sigver_data_msg__get_packed_size
                     (const RsaSigverDataMsg *message)
{
  assert(message->base.descriptor == &rsa_sigver_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_sigver_data_msg__pack
                     (const RsaSigverDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_sigver_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_sigver_data_msg__pack_to_buffer
                     (const RsaSigverDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_sigver_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaSigverDataMsg *
       rsa_sigver_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaSigverDataMsg *)
     protobuf_c_message_unpack (&rsa_sigver_data_msg__descriptor,
                                allocator, len, data);
}
void   rsa_sigver_data_msg__free_unpacked
                     (RsaSigverDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rsa_sigver_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsa_signature_primitive_data_msg__init
                     (RsaSignaturePrimitiveDataMsg         *message)
{
  static const RsaSignaturePrimitiveDataMsg init_value = RSA_SIGNATURE_PRIMITIVE_DATA_MSG__INIT;
  *message = init_value;
}
size_t rsa_signature_primitive_data_msg__get_packed_size
                     (const RsaSignaturePrimitiveDataMsg *message)
{
  assert(message->base.descriptor == &rsa_signature_primitive_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_signature_primitive_data_msg__pack
                     (const RsaSignaturePrimitiveDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_signature_primitive_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_signature_primitive_data_msg__pack_to_buffer
                     (const RsaSignaturePrimitiveDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_signature_primitive_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaSignaturePrimitiveDataMsg *
       rsa_signature_primitive_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaSignaturePrimitiveDataMsg *)
     protobuf_c_message_unpack (&rsa_signature_primitive_data_msg__descriptor,
                                allocator, len, data);
}
void   rsa_signature_primitive_data_msg__free_unpacked
                     (RsaSignaturePrimitiveDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rsa_signature_primitive_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsa_decryption_primitive_data_msg__init
                     (RsaDecryptionPrimitiveDataMsg         *message)
{
  static const RsaDecryptionPrimitiveDataMsg init_value = RSA_DECRYPTION_PRIMITIVE_DATA_MSG__INIT;
  *message = init_value;
}
size_t rsa_decryption_primitive_data_msg__get_packed_size
                     (const RsaDecryptionPrimitiveDataMsg *message)
{
  assert(message->base.descriptor == &rsa_decryption_primitive_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_decryption_primitive_data_msg__pack
                     (const RsaDecryptionPrimitiveDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_decryption_primitive_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_decryption_primitive_data_msg__pack_to_buffer
                     (const RsaDecryptionPrimitiveDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_decryption_primitive_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaDecryptionPrimitiveDataMsg *
       rsa_decryption_primitive_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaDecryptionPrimitiveDataMsg *)
     protobuf_c_message_unpack (&rsa_decryption_primitive_data_msg__descriptor,
                                allocator, len, data);
}
void   rsa_decryption_primitive_data_msg__free_unpacked
                     (RsaDecryptionPrimitiveDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rsa_decryption_primitive_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsa_keygen_en_msg__init
                     (RsaKeygenEnMsg         *message)
{
  static const RsaKeygenEnMsg init_value = RSA_KEYGEN_EN_MSG__INIT;
  *message = init_value;
}
size_t rsa_keygen_en_msg__get_packed_size
                     (const RsaKeygenEnMsg *message)
{
  assert(message->base.descriptor == &rsa_keygen_en_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_keygen_en_msg__pack
                     (const RsaKeygenEnMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_keygen_en_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_keygen_en_msg__pack_to_buffer
                     (const RsaKeygenEnMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_keygen_en_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaKeygenEnMsg *
       rsa_keygen_en_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaKeygenEnMsg *)
     protobuf_c_message_unpack (&rsa_keygen_en_msg__descriptor,
                                allocator, len, data);
}
void   rsa_keygen_en_msg__free_unpacked
                     (RsaKeygenEnMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rsa_keygen_en_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsa_free_key_msg__init
                     (RsaFreeKeyMsg         *message)
{
  static const RsaFreeKeyMsg init_value = RSA_FREE_KEY_MSG__INIT;
  *message = init_value;
}
size_t rsa_free_key_msg__get_packed_size
                     (const RsaFreeKeyMsg *message)
{
  assert(message->base.descriptor == &rsa_free_key_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_free_key_msg__pack
                     (const RsaFreeKeyMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_free_key_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_free_key_msg__pack_to_buffer
                     (const RsaFreeKeyMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_free_key_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaFreeKeyMsg *
       rsa_free_key_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaFreeKeyMsg *)
     protobuf_c_message_unpack (&rsa_free_key_msg__descriptor,
                                allocator, len, data);
}
void   rsa_free_key_msg__free_unpacked
                     (RsaFreeKeyMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rsa_free_key_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rsa_keygen_prime_data_msg__field_descriptors[5] =
{
  {
    "modulus",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenPrimeDataMsg, modulus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenPrimeDataMsg, p),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenPrimeDataMsg, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "e",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenPrimeDataMsg, e),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keygen_success",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenPrimeDataMsg, keygen_success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_keygen_prime_data_msg__field_indices_by_name[] = {
  3,   /* field[3] = e */
  4,   /* field[4] = keygen_success */
  0,   /* field[0] = modulus */
  1,   /* field[1] = p */
  2,   /* field[2] = q */
};
static const ProtobufCIntRange rsa_keygen_prime_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor rsa_keygen_prime_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RsaKeygenPrimeDataMsg",
  "RsaKeygenPrimeDataMsg",
  "RsaKeygenPrimeDataMsg",
  "",
  sizeof(RsaKeygenPrimeDataMsg),
  5,
  rsa_keygen_prime_data_msg__field_descriptors,
  rsa_keygen_prime_data_msg__field_indices_by_name,
  1,  rsa_keygen_prime_data_msg__number_ranges,
  (ProtobufCMessageInit) rsa_keygen_prime_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsa_keygen_data_msg__field_descriptors[20] =
{
  {
    "modulus",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, modulus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, p),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "e",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, e),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xp",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, xp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xp1",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, xp1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xp2",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, xp2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xq",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, xq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xq1",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, xq1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xq2",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, xq2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitlen_in",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, bitlen_in),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitlen1",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, bitlen1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitlen2",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, bitlen2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitlen3",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, bitlen3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitlen4",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, bitlen4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dmp1",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, dmp1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dmq1",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, dmq1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iqmp",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenDataMsg, iqmp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_keygen_data_msg__field_indices_by_name[] = {
  13,   /* field[13] = bitlen1 */
  14,   /* field[14] = bitlen2 */
  15,   /* field[15] = bitlen3 */
  16,   /* field[16] = bitlen4 */
  12,   /* field[12] = bitlen_in */
  2,   /* field[2] = d */
  17,   /* field[17] = dmp1 */
  18,   /* field[18] = dmq1 */
  5,   /* field[5] = e */
  19,   /* field[19] = iqmp */
  0,   /* field[0] = modulus */
  1,   /* field[1] = n */
  3,   /* field[3] = p */
  4,   /* field[4] = q */
  6,   /* field[6] = xp */
  7,   /* field[7] = xp1 */
  8,   /* field[8] = xp2 */
  9,   /* field[9] = xq */
  10,   /* field[10] = xq1 */
  11,   /* field[11] = xq2 */
};
static const ProtobufCIntRange rsa_keygen_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 20 }
};
const ProtobufCMessageDescriptor rsa_keygen_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RsaKeygenDataMsg",
  "RsaKeygenDataMsg",
  "RsaKeygenDataMsg",
  "",
  sizeof(RsaKeygenDataMsg),
  20,
  rsa_keygen_data_msg__field_descriptors,
  rsa_keygen_data_msg__field_indices_by_name,
  1,  rsa_keygen_data_msg__number_ranges,
  (ProtobufCMessageInit) rsa_keygen_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsa_keygen_prov_prime_data_msg__field_descriptors[8] =
{
  {
    "modulus",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenProvPrimeDataMsg, modulus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenProvPrimeDataMsg, n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenProvPrimeDataMsg, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenProvPrimeDataMsg, p),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenProvPrimeDataMsg, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seed",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenProvPrimeDataMsg, seed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "e",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenProvPrimeDataMsg, e),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenProvPrimeDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_keygen_prov_prime_data_msg__field_indices_by_name[] = {
  7,   /* field[7] = cipher */
  2,   /* field[2] = d */
  6,   /* field[6] = e */
  0,   /* field[0] = modulus */
  1,   /* field[1] = n */
  3,   /* field[3] = p */
  4,   /* field[4] = q */
  5,   /* field[5] = seed */
};
static const ProtobufCIntRange rsa_keygen_prov_prime_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor rsa_keygen_prov_prime_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RsaKeygenProvPrimeDataMsg",
  "RsaKeygenProvPrimeDataMsg",
  "RsaKeygenProvPrimeDataMsg",
  "",
  sizeof(RsaKeygenProvPrimeDataMsg),
  8,
  rsa_keygen_prov_prime_data_msg__field_descriptors,
  rsa_keygen_prov_prime_data_msg__field_indices_by_name,
  1,  rsa_keygen_prov_prime_data_msg__number_ranges,
  (ProtobufCMessageInit) rsa_keygen_prov_prime_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsa_siggen_data_msg__field_descriptors[8] =
{
  {
    "modulus",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaSiggenDataMsg, modulus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RsaSiggenDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saltlen",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaSiggenDataMsg, saltlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "e",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSiggenDataMsg, e),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSiggenDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sig",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSiggenDataMsg, sig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSiggenDataMsg, n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "privkey",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaSiggenDataMsg, privkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_siggen_data_msg__field_indices_by_name[] = {
  1,   /* field[1] = cipher */
  3,   /* field[3] = e */
  0,   /* field[0] = modulus */
  4,   /* field[4] = msg */
  6,   /* field[6] = n */
  7,   /* field[7] = privkey */
  2,   /* field[2] = saltlen */
  5,   /* field[5] = sig */
};
static const ProtobufCIntRange rsa_siggen_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor rsa_siggen_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RsaSiggenDataMsg",
  "RsaSiggenDataMsg",
  "RsaSiggenDataMsg",
  "",
  sizeof(RsaSiggenDataMsg),
  8,
  rsa_siggen_data_msg__field_descriptors,
  rsa_siggen_data_msg__field_indices_by_name,
  1,  rsa_siggen_data_msg__number_ranges,
  (ProtobufCMessageInit) rsa_siggen_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsa_sigver_data_msg__field_descriptors[8] =
{
  {
    "modulus",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaSigverDataMsg, modulus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RsaSigverDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saltlen",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaSigverDataMsg, saltlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSigverDataMsg, n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "e",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSigverDataMsg, e),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSigverDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sig",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSigverDataMsg, sig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sig_result",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaSigverDataMsg, sig_result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_sigver_data_msg__field_indices_by_name[] = {
  1,   /* field[1] = cipher */
  4,   /* field[4] = e */
  0,   /* field[0] = modulus */
  5,   /* field[5] = msg */
  3,   /* field[3] = n */
  2,   /* field[2] = saltlen */
  6,   /* field[6] = sig */
  7,   /* field[7] = sig_result */
};
static const ProtobufCIntRange rsa_sigver_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor rsa_sigver_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RsaSigverDataMsg",
  "RsaSigverDataMsg",
  "RsaSigverDataMsg",
  "",
  sizeof(RsaSigverDataMsg),
  8,
  rsa_sigver_data_msg__field_descriptors,
  rsa_sigver_data_msg__field_indices_by_name,
  1,  rsa_sigver_data_msg__number_ranges,
  (ProtobufCMessageInit) rsa_sigver_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsa_signature_primitive_data_msg__field_descriptors[11] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "e",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, e),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, p),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dmp1",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, dmp1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dmq1",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, dmq1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iqmp",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, iqmp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sig_result",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaSignaturePrimitiveDataMsg, sig_result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_signature_primitive_data_msg__field_indices_by_name[] = {
  3,   /* field[3] = d */
  6,   /* field[6] = dmp1 */
  7,   /* field[7] = dmq1 */
  2,   /* field[2] = e */
  8,   /* field[8] = iqmp */
  0,   /* field[0] = msg */
  1,   /* field[1] = n */
  4,   /* field[4] = p */
  5,   /* field[5] = q */
  10,   /* field[10] = sig_result */
  9,   /* field[9] = signature */
};
static const ProtobufCIntRange rsa_signature_primitive_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor rsa_signature_primitive_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RsaSignaturePrimitiveDataMsg",
  "RsaSignaturePrimitiveDataMsg",
  "RsaSignaturePrimitiveDataMsg",
  "",
  sizeof(RsaSignaturePrimitiveDataMsg),
  11,
  rsa_signature_primitive_data_msg__field_descriptors,
  rsa_signature_primitive_data_msg__field_indices_by_name,
  1,  rsa_signature_primitive_data_msg__number_ranges,
  (ProtobufCMessageInit) rsa_signature_primitive_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsa_decryption_primitive_data_msg__field_descriptors[15] =
{
  {
    "modulus",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, modulus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_failures",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, num_failures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "e",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, e),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, p),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dmp1",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, dmp1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dmq1",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, dmq1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iqmp",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, iqmp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dec_result",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, dec_result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "privkey",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaDecryptionPrimitiveDataMsg, privkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_decryption_primitive_data_msg__field_indices_by_name[] = {
  6,   /* field[6] = d */
  13,   /* field[13] = dec_result */
  9,   /* field[9] = dmp1 */
  10,   /* field[10] = dmq1 */
  5,   /* field[5] = e */
  11,   /* field[11] = iqmp */
  0,   /* field[0] = modulus */
  3,   /* field[3] = msg */
  4,   /* field[4] = n */
  1,   /* field[1] = num */
  2,   /* field[2] = num_failures */
  7,   /* field[7] = p */
  14,   /* field[14] = privkey */
  8,   /* field[8] = q */
  12,   /* field[12] = s */
};
static const ProtobufCIntRange rsa_decryption_primitive_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor rsa_decryption_primitive_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RsaDecryptionPrimitiveDataMsg",
  "RsaDecryptionPrimitiveDataMsg",
  "RsaDecryptionPrimitiveDataMsg",
  "",
  sizeof(RsaDecryptionPrimitiveDataMsg),
  15,
  rsa_decryption_primitive_data_msg__field_descriptors,
  rsa_decryption_primitive_data_msg__field_indices_by_name,
  1,  rsa_decryption_primitive_data_msg__number_ranges,
  (ProtobufCMessageInit) rsa_decryption_primitive_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsa_keygen_en_msg__field_descriptors[4] =
{
  {
    "ebuf",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenEnMsg, ebuf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modulus",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenEnMsg, modulus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "privkey",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenEnMsg, privkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nbuf",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RsaKeygenEnMsg, nbuf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_keygen_en_msg__field_indices_by_name[] = {
  0,   /* field[0] = ebuf */
  1,   /* field[1] = modulus */
  3,   /* field[3] = nbuf */
  2,   /* field[2] = privkey */
};
static const ProtobufCIntRange rsa_keygen_en_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor rsa_keygen_en_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RsaKeygenEnMsg",
  "RsaKeygenEnMsg",
  "RsaKeygenEnMsg",
  "",
  sizeof(RsaKeygenEnMsg),
  4,
  rsa_keygen_en_msg__field_descriptors,
  rsa_keygen_en_msg__field_indices_by_name,
  1,  rsa_keygen_en_msg__number_ranges,
  (ProtobufCMessageInit) rsa_keygen_en_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsa_free_key_msg__field_descriptors[1] =
{
  {
    "privkey",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RsaFreeKeyMsg, privkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_free_key_msg__field_indices_by_name[] = {
  0,   /* field[0] = privkey */
};
static const ProtobufCIntRange rsa_free_key_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rsa_free_key_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RsaFreeKeyMsg",
  "RsaFreeKeyMsg",
  "RsaFreeKeyMsg",
  "",
  sizeof(RsaFreeKeyMsg),
  1,
  rsa_free_key_msg__field_descriptors,
  rsa_free_key_msg__field_indices_by_name,
  1,  rsa_free_key_msg__number_ranges,
  (ProtobufCMessageInit) rsa_free_key_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
