/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/sym.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backend_interfaces/protobuf/pb/sym.pb-c.h"
void   sym_data_msg__init
                     (SymDataMsg         *message)
{
  static const SymDataMsg init_value = SYM_DATA_MSG__INIT;
  *message = init_value;
}
size_t sym_data_msg__get_packed_size
                     (const SymDataMsg *message)
{
  assert(message->base.descriptor == &sym_data_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sym_data_msg__pack
                     (const SymDataMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sym_data_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sym_data_msg__pack_to_buffer
                     (const SymDataMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sym_data_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SymDataMsg *
       sym_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SymDataMsg *)
     protobuf_c_message_unpack (&sym_data_msg__descriptor,
                                allocator, len, data);
}
void   sym_data_msg__free_unpacked
                     (SymDataMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sym_data_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sym_data_msg__field_descriptors[10] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SymDataMsg, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iv",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SymDataMsg, iv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cipher",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(SymDataMsg, cipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SymDataMsg, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_len_bits",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SymDataMsg, data_len_bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xts_sequence_no",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SymDataMsg, xts_sequence_no),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xts_data_unit_len",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SymDataMsg, xts_data_unit_len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_loop_final_cj1",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SymDataMsg, inner_loop_final_cj1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integrity_error",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SymDataMsg, integrity_error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kwcipher",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SymDataMsg, kwcipher),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sym_data_msg__field_indices_by_name[] = {
  2,   /* field[2] = cipher */
  3,   /* field[3] = data */
  4,   /* field[4] = data_len_bits */
  7,   /* field[7] = inner_loop_final_cj1 */
  8,   /* field[8] = integrity_error */
  1,   /* field[1] = iv */
  0,   /* field[0] = key */
  9,   /* field[9] = kwcipher */
  6,   /* field[6] = xts_data_unit_len */
  5,   /* field[5] = xts_sequence_no */
};
static const ProtobufCIntRange sym_data_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor sym_data_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SymDataMsg",
  "SymDataMsg",
  "SymDataMsg",
  "",
  sizeof(SymDataMsg),
  10,
  sym_data_msg__field_descriptors,
  sym_data_msg__field_indices_by_name,
  1,  sym_data_msg__number_ranges,
  (ProtobufCMessageInit) sym_data_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
