/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backend_interfaces/protobuf/pb/sym.proto */

#ifndef PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fsym_2eproto__INCLUDED
#define PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fsym_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct SymDataMsg SymDataMsg;


/* --- enums --- */


/* --- messages --- */

struct  SymDataMsg
{
  ProtobufCMessage base;
  ProtobufCBinaryData key;
  ProtobufCBinaryData iv;
  uint64_t cipher;
  ProtobufCBinaryData data;
  uint32_t data_len_bits;
  uint32_t xts_sequence_no;
  uint32_t xts_data_unit_len;
  ProtobufCBinaryData inner_loop_final_cj1;
  uint32_t integrity_error;
  ProtobufCBinaryData kwcipher;
};
#define SYM_DATA_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sym_data_msg__descriptor) \
, {0,NULL}, {0,NULL}, 0, {0,NULL}, 0, 0, 0, {0,NULL}, 0, {0,NULL} }


/* SymDataMsg methods */
void   sym_data_msg__init
                     (SymDataMsg         *message);
size_t sym_data_msg__get_packed_size
                     (const SymDataMsg   *message);
size_t sym_data_msg__pack
                     (const SymDataMsg   *message,
                      uint8_t             *out);
size_t sym_data_msg__pack_to_buffer
                     (const SymDataMsg   *message,
                      ProtobufCBuffer     *buffer);
SymDataMsg *
       sym_data_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sym_data_msg__free_unpacked
                     (SymDataMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SymDataMsg_Closure)
                 (const SymDataMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sym_data_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_backend_5finterfaces_2fprotobuf_2fpb_2fsym_2eproto__INCLUDED */
